systemtarjeta/config/routes.rb
Rails.application.routes.draw do
  resources :movimientos
  resources :almacenbajas
  devise_for :users
  resources :tiendas
  resources :mail_bajas do
    get :enviobaja
  end
  get 'welcome_sys_t/index'
  get 'inicio_usuario/index'
  get 'zona_admin/index'
  get 'tarjetas/index'
  get 'premios/index'
  get 'tiendas/index'

  resources :premios
  resources :tarjeta do
  get :activar
  get :activar_user
  get :des_user

  get :nueva_tarjeta

end
  resources :usuarios
  resources :clientes
  resources :motivos

   root 'welcome_sys_t#index'

  resources :clientes do
     get :bajanormal
   end

   resources :clientes

end

systemtarjeta/app/models/almacenbaja.rb
class Almacenbaja < ActiveRecord::Base
  belongs_to :motivo
  belongs_to :user
  belongs_to :tarjetum

  before_save :default_values
  after_save :baja_tarjeta
cattr_accessor :current_user
   def default_values
     self.user = Almacenbaja.current_user
     self.tarjetum = Tarjetum.find_by(user_id: Almacenbaja.current_user.id)
   end

   def baja_tarjeta
       tarjeta = Tarjetum.find_by(user_id: Almacenbaja.current_user.id)
      tarjeta.fecha_baja = Time.zone.today
      tarjeta.save
   end

end

systemtarjeta/app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

systemtarjeta/app/models/motivo.rb
class Motivo < ActiveRecord::Base
  @motivos = Motivo.all 
end

systemtarjeta/app/models/movimiento.rb
class Movimiento < ActiveRecord::Base
  belongs_to :user
  belongs_to :tarjetum
  belongs_to :premio
end

systemtarjeta/app/models/premio.rb
class Premio < ActiveRecord::Base
end

systemtarjeta/app/models/tabmaestra.rb
class Tabmaestra < ActiveRecord::Base
end

systemtarjeta/app/models/tarjetum.rb
class Tarjetum < ActiveRecord::Base
#belongs_to :usuario
   has_one :usuario
#  has_one :user

validates :user_id, presence: true, uniqueness: true


end

systemtarjeta/app/models/tienda.rb
class Tienda < ActiveRecord::Base
end

systemtarjeta/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         after_save :default_values
         validates :email, presence: true, uniqueness: true

          def default_values
            if self.rol == nil

            self.rol = 'user'
            self.save
          end
          end



end

systemtarjeta/app/models/usuario.rb
class Usuario < ActiveRecord::Base



end

systemtarjeta/app/controllers/premios_controller.rb
class PremiosController < ApplicationController
  before_action :set_premio, only: [:show, :edit, :update, :destroy]

  # GET /premios
  # GET /premios.json
  def index
    @premios = Premio.all
  end

  # GET /premios/1
  # GET /premios/1.json
  def show
  end

  # GET /premios/new
  def new
    @premio = Premio.new
  end

  # GET /premios/1/edit
  def edit
  end

  # POST /premios
  # POST /premios.json
  def create
    @premio = Premio.new(premio_params)

    respond_to do |format|
      if @premio.save
        format.html { redirect_to zona_admin_index_path, notice: 'Premio was successfully created.' }
        format.json { render :show, status: :created, location: @premio }
      else
        format.html { render :new }
        format.json { render json: @premio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /premios/1
  # PATCH/PUT /premios/1.json
  def update
    respond_to do |format|
      if @premio.update(premio_params)
        format.html { redirect_to zona_admin_index_path, notice: 'Premio was successfully updated.' }
        format.json { render :show, status: :ok, location: @premio }
      else
        format.html { render :edit }
        format.json { render json: @premio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /premios/1
  # DELETE /premios/1.json
  def destroy
    @premio.fecha_baja = Time.zone.today
    @premio.save    respond_to do |format|
      format.html { redirect_to premios_url, notice: 'Premio fue dado de baja con éxito' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_premio
      @premio = Premio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def premio_params
      params.require(:premio).permit(:concepto, :stock, :puntos, :fecha_baja, :photo)
    end
end

systemtarjeta/app/helpers/almacenbajas_helper.rb
module AlmacenbajasHelper
end

systemtarjeta/app/helpers/application_helper.rb
module ApplicationHelper
end

systemtarjeta/app/helpers/clientes_helper.rb
module ClientesHelper
end

systemtarjeta/app/helpers/mail_bajas_helper.rb
module MailBajasHelper
end

systemtarjeta/app/helpers/motivos_helper.rb
module MotivosHelper
end

systemtarjeta/app/helpers/movimientos_helper.rb
module MovimientosHelper
end

systemtarjeta/app/helpers/premios_helper.rb
module PremiosHelper
end

systemtarjeta/app/helpers/tarjeta_helper.rb
module TarjetaHelper
end

systemtarjeta/app/helpers/tiendas_helper.rb
module TiendasHelper
end

systemtarjeta/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

systemtarjeta/app/helpers/welcome_sys_t_helper.rb
module WelcomeSysTHelper
end

systemtarjeta/app/helpers/zona_admin_helper.rb
module ZonaAdminHelper
end

systemtarjeta/app/views/premios/_form.html.erb
<%= form_for(@premio) do |f| %>
  <% if @premio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@premio.errors.count, "error") %> prohibited this premio from being saved:</h2>

      <ul>
      <% @premio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :concepto %><br>
    <%= f.text_field :concepto %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="field">
    <%= f.label :puntos %><br>
    <%= f.number_field :puntos %>
  </div>
 
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

systemtarjeta/app/views/premios/_formedit.html.erb
<%= form_for(@premio) do |f| %>
  <% if @premio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@premio.errors.count, "error") %> prohibited this premio from being saved:</h2>

      <ul>
      <% @premio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   
  <div class="field">
    <%= f.label :puntos %><br>
    <%= f.number_field :puntos %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

systemtarjeta/app/views/premios/_index.html.erb
<table class="table table-striped">  <thead>
    <tr>
      <th>Nombre</th>
      <th>Puntos</th>
      </tr>
  </thead>

  <tbody>
    <% premios = Premio.where(fecha_baja:nil) %>


 <% premios.each do |gift| %>
<tr>      <td><%= gift.concepto %></td>
      <td><%= gift.puntos %></td>

      <td>
    </td></tr>

  </tbody>
</table>


<% if tarj.fecha_baja == nil %>

<!-- Trigger the modal with a button -->
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Baja Tarjeta</button>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Formulario Baja</h4>
      </div>
      <div class="modal-body">
        <p>Selecciona el motivo de la baja</p>
        <%= render "almacenbajas/form" %>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>

  </div>
</div>

<% else %>
<td><%= link_to "Activar",  tarjetum_activar_path(tarj), :class =>'btn btn-success', data: { confirm: '¿Seguro que desea activar la tarjeta?'} %></td>

  <% end %>

<% end %>

systemtarjeta/app/views/premios/edit.html.erb
<nav class="navbar   navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Points4All</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li class="active"><%= link_to "Home", root_path %> </li>
      <% if current_user %>
      <% if current_user.rol == 'admin'%>
      <li class="active"><%= link_to "Panel Admin", zona_admin_index_path %> </li>

      <%end%>
    <li>   <%= link_to 'Welcome ' + current_user.nombre, inicio_usuario_index_path %></li>
    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
<% else %>
  <li>  <%= link_to 'Login', new_user_session_path %></li>
<% end %>


<li><a href="#">Contacto</a></li>
<li><a href="#">Ayuda</a></li>
    </ul>
  </div>
</nav>

<div class="container">

<h1>Editar Premio</h1>
<div class="panel-group">
<div class="panel panel-primary">
    <div class="panel-heading">Editar Premio</div>
    <div class="panel-body">

<%= render 'form' %>

<%= link_to 'Show', @premio %> |
<%= link_to 'Back', premios_path %>


</div>
</div>

</div>
</div>
<%= image_tag 'indexFondo111.png' %>

systemtarjeta/app/views/premios/index.html.erb
<nav class="navbar   navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Points4All</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li class="active"><%= link_to "Home", root_path %> </li>
      <% if current_user %>
      <% if current_user.rol == 'admin'%>
      <li class="active"><%= link_to "Panel Admin", zona_admin_index_path %> </li>

      <%end%>
    <li>   <%= link_to 'Welcome ' + current_user.nombre, inicio_usuario_index_path %></li>
    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
<% else %>
  <li>  <%= link_to 'Login', new_user_session_path %></li>
<% end %>


<li><a href="#">Contacto</a></li>
<li><a href="#">Ayuda</a></li>
    </ul>
  </div>
</nav>
<p id="notice"><%= notice %></p>
<div class="container">
<h1> Premios</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Imagen</th>

      <th>Concepto</th>
      <th>Stock</th>
      <th>Puntos</th>
      <% if current_user %>
     <% if current_user.rol == 'admin'%>
       <th>Fecha baja</th>
      <%end%>
      <%end%>      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if current_user %>
    <% if current_user.rol != 'admin'%>
      <% @premios = Premio.where(fecha_baja:nil) %>
      <%else%>
      <%@premios = Premio.all%>
      <%end%>
<%end%>
    <% @premios.each do |premio| %>
      <tr>
        <td><%= image_tag premio.photo, :class => "img-responsive"%></td>
        <td><%= premio.concepto %></td>
        <td><%= premio.stock %></td>
        <td><%= premio.puntos %></td>
        <td><%= link_to 'Visitar', premio %></td>

        <% if current_user %>
        <% if current_user.rol == 'admin'%>
        <td><%= premio.fecha_baja %></td>

         <td><%= link_to 'Editar', edit_premio_path(premio) %></td>
        <td><%= link_to 'Dar de baja', premio, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
        <%end%>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user %>
<% if current_user.rol == 'admin'%>
<%= link_to 'New Premio', new_premio_path %>
<%end%>
<%end%>
</div>

systemtarjeta/app/views/premios/new.html.erb
<nav class="navbar   navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Points4All</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li class="active"><%= link_to "Home", root_path %> </li>
      <% if current_user %>
      <% if current_user.rol == 'admin'%>
      <li class="active"><%= link_to "Panel Admin", zona_admin_index_path %> </li>

      <%end%>
    <li>   <%= link_to 'Welcome ' + current_user.nombre, inicio_usuario_index_path %></li>
    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
<% else %>
  <li>  <%= link_to 'Login', new_user_session_path %></li>
<% end %>


<li><a href="#">Contacto</a></li>
<li><a href="#">Ayuda</a></li>
    </ul>
  </div>
</nav>

<div class="container">

<h2>Formulario Inscripción</h2>
<div class="panel-group">
<div class="panel panel-primary">
    <div class="panel-heading">Nueo Premio </div>
    <div class="panel-body">


<%= render 'form' %>

<%= link_to 'Back', premios_path %>

</div>
</div>

</div>
</div>
<%= image_tag 'indexFondo111.png' %>

systemtarjeta/app/views/premios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Concepto:</strong>
  <%= @premio.concepto %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @premio.stock %>
</p>

<p>
  <strong>Puntos:</strong>
  <%= @premio.puntos %>
</p>

<p>
  <strong>Fecha baja:</strong>
  <%= @premio.fecha_baja %>
</p>

<%= link_to 'Edit', edit_premio_path(@premio) %> |
<%= link_to 'Back', premios_path %>