systemtarjeta/config/routes.rb
Rails.application.routes.draw do
  resources :movimientos
  resources :almacenbajas
  devise_for :users
  resources :tiendas
  resources :mail_bajas do
    get :enviobaja
  end
  get 'welcome_sys_t/index'
  get 'inicio_usuario/index'
  get 'zona_admin/index'
  get 'tarjetas/index'
  get 'premios/index'
  get 'tiendas/index'

  resources :premios
  resources :tarjeta do
  get :activar
  get :activar_user
  get :des_user

  get :nueva_tarjeta

end
  resources :usuarios
  resources :clientes
  resources :motivos

   root 'welcome_sys_t#index'

  resources :clientes do
     get :bajanormal
   end

   resources :clientes

end

systemtarjeta/app/models/almacenbaja.rb
class Almacenbaja < ActiveRecord::Base
  belongs_to :motivo
  belongs_to :user
  belongs_to :tarjetum

  before_save :default_values
  after_save :baja_tarjeta
cattr_accessor :current_user
   def default_values
     self.user = Almacenbaja.current_user
     self.tarjetum = Tarjetum.find_by(user_id: Almacenbaja.current_user.id)
   end

   def baja_tarjeta
       tarjeta = Tarjetum.find_by(user_id: Almacenbaja.current_user.id)
      tarjeta.fecha_baja = Time.zone.today
      tarjeta.save
   end

end

systemtarjeta/app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

systemtarjeta/app/models/motivo.rb
class Motivo < ActiveRecord::Base
  @motivos = Motivo.all 
end

systemtarjeta/app/models/movimiento.rb
class Movimiento < ActiveRecord::Base
  belongs_to :user
  belongs_to :tarjetum
  belongs_to :premio
end

systemtarjeta/app/models/premio.rb
class Premio < ActiveRecord::Base
end

systemtarjeta/app/models/tabmaestra.rb
class Tabmaestra < ActiveRecord::Base
end

systemtarjeta/app/models/tarjetum.rb
class Tarjetum < ActiveRecord::Base
#belongs_to :usuario
   has_one :usuario
#  has_one :user

validates :user_id, presence: true, uniqueness: true


end

systemtarjeta/app/models/tienda.rb
class Tienda < ActiveRecord::Base
end

systemtarjeta/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         after_save :default_values
         validates :email, presence: true, uniqueness: true

          def default_values
            if self.rol == nil

            self.rol = 'user'
            self.save
          end
          end



end

systemtarjeta/app/models/usuario.rb
class Usuario < ActiveRecord::Base



end

systemtarjeta/app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json


      def bajanormal
          @cliente = Cliente.find(params[:cliente_id])
          @cliente.fecha_baja = Time.zone.today
          @cliente.save
          respond_to do |format|
            format.html { redirect_to :back}
            format.json { head :no_content }
          end
        end


  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nombre, :apellidos,:telefono,:email)
    end


end

systemtarjeta/app/helpers/almacenbajas_helper.rb
module AlmacenbajasHelper
end

systemtarjeta/app/helpers/application_helper.rb
module ApplicationHelper
end

systemtarjeta/app/helpers/clientes_helper.rb
module ClientesHelper
end

systemtarjeta/app/helpers/mail_bajas_helper.rb
module MailBajasHelper
end

systemtarjeta/app/helpers/motivos_helper.rb
module MotivosHelper
end

systemtarjeta/app/helpers/movimientos_helper.rb
module MovimientosHelper
end

systemtarjeta/app/helpers/premios_helper.rb
module PremiosHelper
end

systemtarjeta/app/helpers/tarjeta_helper.rb
module TarjetaHelper
end

systemtarjeta/app/helpers/tiendas_helper.rb
module TiendasHelper
end

systemtarjeta/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

systemtarjeta/app/helpers/welcome_sys_t_helper.rb
module WelcomeSysTHelper
end

systemtarjeta/app/helpers/zona_admin_helper.rb
module ZonaAdminHelper
end

systemtarjeta/app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellidos %><br>
    <%= f.text_field :apellidos %>
  </div>

  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </div>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

systemtarjeta/app/views/clientes/edit.html.erb
<h1>Editing Cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

systemtarjeta/app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron text-center">
  <h1>SystemCard</h1>
  <p> Enterprise Solutions</p>
</div>

<div class="container">
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Home</a>
    </div>
    <ul class="nav navbar-nav">
       <li class="name"> 'CongressParticipant'</li>
       <li class="name">'Sesiones'</li>
       <li class="name">'Congresos'</li>
    </ul>
  </div>
</nav>
<table class="table table-striped">

  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellidos</th>
      <th>Telefono</th>
      <th>E-mail</th>
      <th>Fecha Baja</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nombre %></td>
        <td><%= cliente.apellidos %></td>
        <td><%= cliente.telefono %></td>
        <td><%= cliente.email %></td>
        <td><%= cliente.fecha_baja %></td>

        <td><%= link_to 'Ver', cliente %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <% if cliente.fecha_baja.blank?%>
        <td><%= link_to 'Baja',cliente_bajanormal_path(cliente), data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Cliente', new_cliente_path %>

</div>

systemtarjeta/app/views/clientes/new.html.erb
<h1>New Cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>

systemtarjeta/app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @cliente.nombre %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @cliente.apellidos %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @cliente.telefono %>
</p>

<p>
  <strong>E-mail:</strong>
  <%= @cliente.email %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>