systemtarjeta/config/routes.rb
Rails.application.routes.draw do
  resources :movimientos
  resources :almacenbajas
  devise_for :users
  resources :tiendas
  resources :mail_bajas do
    get :enviobaja
  end
  get 'welcome_sys_t/index'
  get 'inicio_usuario/index'
  get 'zona_admin/index'
  get 'tarjetas/index'
  get 'premios/index'
  get 'tiendas/index'

  resources :premios
  resources :tarjeta do
  get :activar
  get :activar_user
  get :des_user

  get :nueva_tarjeta

end
  resources :usuarios
  resources :clientes
  resources :motivos

   root 'welcome_sys_t#index'

  resources :clientes do
     get :bajanormal
   end

   resources :clientes

end

systemtarjeta/app/models/almacenbaja.rb
class Almacenbaja < ActiveRecord::Base
  belongs_to :motivo
  belongs_to :user
  belongs_to :tarjetum

  before_save :default_values
  after_save :baja_tarjeta
cattr_accessor :current_user
   def default_values
     self.user = Almacenbaja.current_user
     self.tarjetum = Tarjetum.find_by(user_id: Almacenbaja.current_user.id)
   end

   def baja_tarjeta
       tarjeta = Tarjetum.find_by(user_id: Almacenbaja.current_user.id)
      tarjeta.fecha_baja = Time.zone.today
      tarjeta.save
   end

end

systemtarjeta/app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

systemtarjeta/app/models/motivo.rb
class Motivo < ActiveRecord::Base
  @motivos = Motivo.all 
end

systemtarjeta/app/models/movimiento.rb
class Movimiento < ActiveRecord::Base
  belongs_to :user
  belongs_to :tarjetum
  belongs_to :premio
end

systemtarjeta/app/models/premio.rb
class Premio < ActiveRecord::Base
end

systemtarjeta/app/models/tabmaestra.rb
class Tabmaestra < ActiveRecord::Base
end

systemtarjeta/app/models/tarjetum.rb
class Tarjetum < ActiveRecord::Base
#belongs_to :usuario
   has_one :usuario
#  has_one :user

validates :user_id, presence: true, uniqueness: true


end

systemtarjeta/app/models/tienda.rb
class Tienda < ActiveRecord::Base
end

systemtarjeta/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         after_save :default_values
         validates :email, presence: true, uniqueness: true

          def default_values
            if self.rol == nil

            self.rol = 'user'
            self.save
          end
          end



end

systemtarjeta/app/models/usuario.rb
class Usuario < ActiveRecord::Base



end

systemtarjeta/app/controllers/zona_admin_controller.rb
class ZonaAdminController < ApplicationController
end

systemtarjeta/app/helpers/almacenbajas_helper.rb
module AlmacenbajasHelper
end

systemtarjeta/app/helpers/application_helper.rb
module ApplicationHelper
end

systemtarjeta/app/helpers/clientes_helper.rb
module ClientesHelper
end

systemtarjeta/app/helpers/mail_bajas_helper.rb
module MailBajasHelper
end

systemtarjeta/app/helpers/motivos_helper.rb
module MotivosHelper
end

systemtarjeta/app/helpers/movimientos_helper.rb
module MovimientosHelper
end

systemtarjeta/app/helpers/premios_helper.rb
module PremiosHelper
end

systemtarjeta/app/helpers/tarjeta_helper.rb
module TarjetaHelper
end

systemtarjeta/app/helpers/tiendas_helper.rb
module TiendasHelper
end

systemtarjeta/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

systemtarjeta/app/helpers/zona_admin_helper.rb
module ZonaAdminHelper
end

systemtarjeta/app/views/zona_admin/index.html.erb
<head>    <title>New Age - Start Bootstrap Theme</title>


      <!-- Bootstrap Core CSS -->
      <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

      <!-- Custom Fonts -->
      <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">

      <!-- Plugin CSS -->
      <link rel="stylesheet" href="vendor/font-awesome/css/font-awesome.min.css">
      <link rel="stylesheet" href="vendor/simple-line-icons/css/simple-line-icons.css">
      <link rel="stylesheet" href="vendor/device-mockups/device-mockups.min.css">

      <!-- Theme CSS -->
      <link href="css/new-age.min.css" rel="stylesheet">


<style>
      .background_image {
          background: url('/assets/indexFondo.PNG');


      }
      .jumbotron{background:transparent;}

</style>
</head>

<nav class="navbar   navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Points4All</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li class="active"><%= link_to "Home", root_path %> </li>
      <% if current_user %>
      <% if current_user.rol == 'admin'%>
      <li class="active"><%= link_to "Panel Admin", zona_admin_index_path %> </li>

      <%end%>
    <li>   <%= link_to 'Welcome ' + current_user.nombre, inicio_usuario_index_path %></li>
    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
<% else %>
  <li>  <%= link_to 'Login', new_user_session_path %></li>
<% end %>


<li><a href="#">Contacto</a></li>
<li><a href="#">Ayuda</a></li>
    </ul>
  </div>
</nav>
<div class="container">
<h1>Hola <%= current_user.nombre %></h1>
<h2>-- Zona Admin --</h2>

<h2>¿Que quieres hacer?</h2>

<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
        Altas</a>
      </h4>
    </div>
    <div id="collapse1" class="panel-collapse collapse in">
      <div class="panel-body">
        <%= link_to 'Tienda', new_tienda_path, :class =>'btn btn-success' %>
        <%= link_to 'Premio', new_premio_path, :class =>'btn btn-success' %>

       </div>
    </div>
  </div>

   <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
       Report -  Mantenimiento</a>
      </h4>
    </div>
    <div id="collapse2" class="panel-collapse collapse">
      <div class="panel-body">
         <%= link_to "Movimientos",  tiendas_path, :class =>'btn btn-success' %>
         <%= link_to "Tiendas",  tiendas_path, :class =>'btn btn-success'  %>
        <%= link_to "Premios",  premios_path, :class =>'btn btn-success'  %>

       </div>
    </div>
  </div>

  <div class="panel panel-default">
   <div class="panel-heading">
     <h4 class="panel-title">
       <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">
      Usuarios</a>
     </h4>
   </div>
   <div id="collapse3" class="panel-collapse collapse">
     <div class="panel-body">
       <table class="table table-striped">
         <thead>
         <tr>
           <th>Nombre</th>
           <th>Apellidos</th>
           <th>Direccion</th>
           <th>Telefono</th>
           <th>Email</th>

           <th colspan="3"></th>
         </tr>
       </thead>

 <tbody>
   <% usuarios = User.all%>
   <% usuarios.each do |usuario|%>
     <tr>

       <td><%= usuario.nombre %></td>
       <td><%= usuario.apellidos %></td>
       <td><%= usuario.direccion %></td>
       <td><%= usuario.telefono %></td>
       <td><%= usuario.email %></td>

     </tr>
     <% end %>

 </tbody>
</table>
       </div>
   </div>
 </div>


      </div>
   </div>
</div>
</div>